#docker compose -f docker-compose.test.yml --env-file .env.test up
include:
  - path: ./docker-compose.yml
services:
  model-handler-service:
    image:  ghcr.io/baddou666/projet-metier/test/model-handler:latest
    ports:
      - 8080:8080
    