services:
  redis-server:
    image: redis:7-alpine
    command: >
      redis-server 
      --port ${REDIS_INTERNAL_PORT}
      --requirepass ${REDIS_PASSWORD}
      --save "" 
      --appendonly no
