include:
  - path: ../../backend-services/https-proxy-service/docker-compose.yml
  - path: ../../backend-services/rate-limiting-service/docker-compose.yml
  - path: ../../backend-services/redis-shared-memory-service/docker-compose.yml
services:
  https-proxy:
    networks:
      - proxy-ratelimiter-net
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - rate-limiting-service
  rate-limiting-service:
    image: ghcr.io/baddou666/projet-metier/test/rate-limiter:latest
    container_name: ${PROXY_TARGET_HOST}
    networks:
        - proxy-ratelimiter-net
        - redis-ratelimiter-net
    depends_on:
      - redis-server

  redis-server:
    container_name: ${REDIS_HOST}
    networks:
        - redis-ratelimiter-net
    
networks:
  proxy-ratelimiter-net:
    driver: bridge
    name: proxy-ratelimiter-net
  redis-ratelimiter-net:
    driver: bridge
    name: redis-ratelimiter-net

