api-gateway-service.security.authentication.anonym-jwt.expiration-sec=300
api-gateway-service.security.authentication.anonym-jwt.generation-delay-ms=0
api-gateway-service.security.authentication.token-rate-limit.max-token-per-ip=5
api-gateway-service.security.authentication.token-rate-limit.window-size-per-ip=60
