services:
  # Votre application Spring Boot
  rate-limiting-service:
    image: ghcr.io/baddou666/projet-metier/final/rate-limiter:latest
    container_name: rate-limiting-service
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_INTERNAL_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWKS_SRC_URL=${JWKS_SRC_URL}
    expose:
      - 8080
    volumes:
      - ./config:/workspace/config
      - ./logs:/workspace/logs