deployment_environment: staging
ghcr_registry: ghcr.io
ghcr_username: baddou666
project_repo_url: "https://github.com/Baddou666/project-metier.git"
project_repo_version: main
project_parent_dir: "/opt/projet-metier-staging"
project_repo_dir: "/opt/projet-metier-staging/project-metier"
staging_deploy_dir: "/opt/projet-metier-staging/project-metier/deploy/staging"
deploy_stack: true
stack_name: "ai-detector-staging"
staging_env_file: ".env"
staging_rendered_stack_file: "/tmp/ai-detector-staging-compose.yml"
render_staging_env: true
staging_backend_api_url: "https://ai-detect-staging"
staging_frontend_env: production
staging_grafana_root_url: "http://localhost:3000"
hf_model_repo_url: "https://huggingface.co/Mitsuman/distilbert"
hf_model_repo_version: main
