services:
  # Votre application Spring Boot
  token-manager-service:
    image: ghcr.io/baddou666/projet-metier/staging/token-manager:v1.0.0
    container_name: token-manager
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_INTERNAL_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - FORWARDED_CLIENT_IP_HEADER=${FORWARDED_CLIENT_IP_HEADER}
      - AUTH_GATEWAY_SHARED_SECRET_HEADER=${AUTH_GATEWAY_SHARED_SECRET_HEADER}
      - AUTH_GATEWAY_SHARED_SECRET=${AUTH_GATEWAY_SHARED_SECRET}
    expose:
      - 8080
    volumes:
      - ./config:/workspace/config
      - ./logs:/workspace/logs
      - ./certs:/workspace/certs
