api-gateway-service.security.ratelimiting.max-attempts-per-token=60
api-gateway-service.security.ratelimiting.window-size-per-token=60
api-gateway-service.security.ratelimiting.max-token-per-ip=5
api-gateway-service.security.ratelimiting.window-size-per-ip=60