include:
  - path: ../../backend-services/loki-service/docker-compose.yml
  - path: ../../backend-services/promtail-service/docker-compose.yml
  - path: ../../backend-services/grafana-service/docker-compose.yml

services:
  loki:
    networks:
      - monitoring

  promtail:
    networks:
      - monitoring
    depends_on:
      - loki

  grafana:
    networks:
      - monitoring
    depends_on:
      - loki

networks:
  monitoring:
    name: monitoring-network
    driver: bridge
