services:
  # Votre application Spring Boot
  token-manager-service:
    image: ghcr.io/baddou666/projet-metier/final/token-manager:latest
    container_name: token-manager
    environment:
      - PERMISSION_SERVER_URL=${PERMISSION_SERVER_URL}
    expose:
      - 8080
    volumes:
      - ./config:/workspace/config
      - ./logs:/workspace/logs
      - ./certs:/workspace/certs