services:
  redis:
    image: redis:7-alpine
    container_name: redis-shared-memory
    # On retire les flags de limitation de mémoire
    command: >
      redis-server 
      --save "" 
      --appendonly no
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - redis-ratelimiter-network
networks:
  redis-ratelimiter-network:
    external: true