
services:
  model-handler-service:
    image:  ghcr.io/baddou666/projet-metier/staging/model-handler:v1.0.0
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DB_PASSWORD=${POSTGRESDB_PASSWORD}
      - IS_ANONYM_USER_HEADER=${IS_ANONYM_USER_HEADER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - MODEL_URL=${MODEL_URL}
      - POSTGRES_URL=${POSTGRES_URL}
      - BPL_JVM_THREAD_COUNT=${BPL_JVM_THREAD_COUNT}
      - JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS}
    expose:
      - 8080
