include:
  - path: ./token-manager/docker-compose.yml
  - path: ./rate-limiting/docker-compose.yml
  - path: ../redis-shared-memory-service/docker-compose.yml

services:
  token-manager-service:
    image: ghcr.io/baddou666/projet-metier/test/token-manager:latest
    networks:
      - auth-net
    ports:
      - 80:8080

  rate-limiting-service:
    image: ghcr.io/baddou666/projet-metier/test/rate-limiter:v1.1.0

    ports:
    - 81:8080
    networks:
      - auth-net
    depends_on:
      - redis-server
      - token-manager-service
  redis-server:
    networks:
      - auth-net
networks:
  auth-net:
    driver: bridge