# docker compose -f "docker-compose.test.yml" up
include:
  - path: ./docker-compose.yml
services:
  transformer-model-service:
    image: ghcr.io/baddou666/projet-metier/dev/transformer-model:test
    ports:
      - 8000:8000
