spring.application.name=rate-limiter
spring.config.import=optional:classpath:config/ratelimiting.properties,optional:classpath:config/server.properties,optional:classpath:/config/routes.properties
api-gateway-service.data.redis.redis-host=${REDIS_HOST}
api-gateway-service.data.redis.redis-port=${REDIS_PORT}
api-gateway-service.data.redis.redis-password=${REDIS_PASSWORD}
api-gateway-service.security.auth-sevice.url=${JWKS_SRC_URL}
api-gateway-service.routing.token-route-id=${TOKEN_ROUTE_ID}
api-gateway-service.security.authentication.gateway-shared-secret-header=${AUTH_GATEWAY_SHARED_SECRET_HEADER}
api-gateway-service.security.authentication.gateway-shared-secret=${AUTH_GATEWAY_SHARED_SECRET}
api-gateway-service.network.real-ip-header=${REAL_IP_HEADER}
api-gateway-service.network.forwarded-client-ip-header=${FORWARDED_CLIENT_IP_HEADER}
api-gateway-service.network.trusted-forwarded-headers=${TRUSTED_FORWARDED_HEADERS}


spring.security.user.name=none
spring.security.user.password=none
