spring.application.name=rate-limiter
spring.config.import=optional:classpath:config/ratelimiting.properties,optional:classpath:config/server.properties
api-gateway-service.data.redis.redis-host=${REDIS_HOST}
api-gateway-service.data.redis.redis-port=${REDIS_PORT}
api-gateway-service.data.redis.redis-password=${REDIS_PASSWORD}
api-gateway-service.security.auth-sevice.url=${JWKS_SRC_URL}

# Logging configuration
logging.file.name=logs/rate-limiter.log
logging.level.root=INFO
logging.level.aidetector=DEBUG
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n