[dev_vms]
projet-metier-node ansible_host=ai-detect-dev ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3

[dev_vms:vars]
ansible_become=true
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
