#tester si le proxy nginx fonctionne correctement avec un serveur de test
include:
  - path: ./docker-compose.yml
services:
  https-proxy:
    ports:
    #ouvrir deux port pour activer la redirection
      - "80:80"
      - "443:443"