#tester si le proxy nginx fonctionne correctement avec un serveur de test
include:
  - path: ./docker-compose.yml
services:
  https-proxy:
    ports:
    #ouvrir deux port pour activer la redirection
      - "80:80"
      - "443:443"
  test-server:
    image: kennethreitz/httpbin
    ports:
      #ouvrir un port directement du serveur pour comparer
      - "8000:80"