api-gateway-service.routing.public-routes[0].id=${TOKEN_ROUTE_ID}
api-gateway-service.routing.public-routes[0].path=/api/anonym-token/get
api-gateway-service.routing.public-routes[0].uri=${TOKEN_MANAGER_SERVICE_URI}


api-gateway-service.routing.protected-routes[0].id=ai-detector-route
api-gateway-service.routing.protected-routes[0].path=/api/ai-detector/**
api-gateway-service.routing.protected-routes[0].uri=${AI_DETECTOR_SERVICE_URI}