spring.cloud.gateway.server.webflux.routes[0].id=${TOKEN_ROUTE_ID}
spring.cloud.gateway.server.webflux.routes[0].uri=${TOKEN_MANAGER_SERVICE_URI}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/anonym-token/get
spring.cloud.gateway.server.webflux.routes[0].metadata.access-policy=public-token

spring.cloud.gateway.server.webflux.routes[1].id=ai-detector-route
spring.cloud.gateway.server.webflux.routes[1].uri=${AI_DETECTOR_SERVICE_URI}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/ai-detector/**
spring.cloud.gateway.server.webflux.routes[1].metadata.access-policy=protected-anonymous