[swarm_managers]
staging-manager ansible_host=ai-detect-staging-manager ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3 swarm_role=manager node_label=manager

[swarm_workers_backend]
staging-backend ansible_host=ai-detect-staging-backend ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3 swarm_role=worker node_label=backend

[swarm_workers_ai]
staging-ai ansible_host=ai-detect-staging-ai ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3 swarm_role=worker node_label=ai

[swarm_workers_data]
staging-data ansible_host=ai-detect-staging-data ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3 swarm_role=worker node_label=data

[swarm_workers:children]
swarm_workers_backend
swarm_workers_ai
swarm_workers_data

[swarm_nodes:children]
swarm_managers
swarm_workers

[swarm_nodes:vars]
ansible_become=true
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
