spring.application.name=api-gateway


api-gateway-service.security.jwt.secret-key=${JWT_SECRET_KEY}
api-gateway-service.security.jwt.expirationSec=3600
api-gateway-service.security.jwt.minJwtSecretLength=32

api-gateway-service.security.hash.algorithme="HmacSHA256"
api-gateway-service.security.hash.salt=${HASH_SALT}
api-gateway-service.security.ratelimiting.maxPerMinAttempts=${MAX_USER_MIN_ATTEMPS}
api-gateway-service.security.ratelimiting.tokenGenerationDelayMs=500
api-gateway-service.data.redis.redisHost=${REDIS-HOST}
api-gateway-service.data.redis.redisPort=${REDIS-PORT:6379}
api-gateway-service.data.redis.redisPassword=${REDIS-PASSWORD}

