spring.application.name=Authentication

spring.config.import=optional:classpath:config/jwt.properties,optional:classpath:config/server.properties
api-gateway-service.security.jwt.secret-key=${JWT_SECRET_KEY}
