spring.application.name=Authentication

spring.config.import=optional:classpath:config/token.properties,optional:classpath:config/server.properties

api-gateway-service.security.authentication.jwt.private-key-resource=classpath:certs/jwt-private.pem

api-gateway-service.security.authentication.token.permission-server-url=${PERMISSION_SERVER_URL:bruuuh.com}



logging.file.name=logs/token-manager.log
logging.level.root=INFO
logging.level.aidetector=DEBUG
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n