[proxmox_vms]
projet-metier-node ansible_host=cloud-node-01 ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3

[proxmox_vms:vars]
ansible_become=true
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
