#permet de pouvoir executer appliquer terraform et ansible depuis n'importe qu'elle machine
#Créer l'image ou l'éxécuter: docker compose up -d
#forcer un rebuild de l'image: docker compose build
#attacher le terminal: docker exec -it linux-devbox bash
services:
  devbox:
    build: .
    container_name: linux-devbox
    tty: true
    stdin_open: true

    volumes:
      - ./:/root/host
      - devbox_ssh_keys:/root/.ssh
    command: bash -c "rm -f /root/.ssh/known* && bash"

volumes:
  devbox_ssh_keys:
